# server configuration
server:
  ssl:
    key-store: \MomoJarJava1108\192_168_1_6_pdn.jks
    key-store-password: klUoPYi9O0aWr391
    key-store-type: jks
    key-password: klUoPYi9O0aWr391
    protocol: TLS
    enabled-protocols: TLSv1.2
  port: 8945

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mysql:thin://127.0.0.1:3306/messagegateway
    username: root
    password: mysql
    driver-class-name: org.drizzle.jdbc.DrizzleDriver

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host: localhost
  protocol: http

callbackconfig:
  host: 0.0.0.0
  protocol: http
  port: 5000

application:
  version: 1.0.0

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

providerSource:
  fromDatabase: disabled
  fromyml: enabled

providerKeys:
  telerivetApiKey: eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl
  telerivetProjectId: PJ5ff552ce01d2978c

logging:
  level:
    ROOT: ERROR
