# server configuration
server:
  port: 8945
ssl:
  key-store: "classpath:tomcat.jks"
  key-store-password: "L3ts3ncryptp455w0rd"
  key-password: "L3ts3ncryptp455w0rd"
  key-store-type: "jks"
  key-alias: tomcat

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql:thin://localhost:3306/messagegateway
    username: root
    password: mysql
    driver-class-name: org.drizzle.jdbc.DrizzleDriver

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host-address: 212.88.125.189
  protocol: https
