# server configuration
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: L3ts3ncryptp455w0rd
    key-store-type: pkcs12
    key-alias: springboot
    key-password: L3ts3ncryptp455w0rd
    port: 8945

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/messagegateway
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host-address: 212.88.125.189
  protocol: https
